### ISSUE TITLE
ValueError: Invalid codec: rav1e

### ISSUE THREAD

**Issue by k128** [fdintino/pillow-avif-plugin#25]
Windows 10
Python 3.11.2
pillow_avif_plugin-1.3.1-cp311-cp311-win_amd64.whl

I get the following error trying to use rav1e to save:
```
>>> im.save('rav.avif',save_all=True,codec='rav1e')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python311\Lib\site-packages\PIL\Image.py", line 2413, in save
    save_handler(self, fp, filename)
  File "C:\Program Files\Python311\Lib\site-packages\pillow_avif\AvifImagePlugin.py", line 111, in _save_all
    _save(im, fp, filename, save_all=True)
  File "C:\Program Files\Python311\Lib\site-packages\pillow_avif\AvifImagePlugin.py", line 184, in _save
    enc = _avif.AvifEncoder(
          ^^^^^^^^^^^^^^^^^^
```

**Comment by fdintino** [comment]
You're getting this issue because I'm not currently bundling rav1e in the windows wheels. But I plan to do so in the next point release.
