### ISSUE TITLE
Use pixtral processor found AttributeError: 'AvifImageFile' object has no attribute '_decoder'

### ISSUE THREAD

**Issue by sdbds** [fdintino/pillow-avif-plugin#64]
pillow==10.2.0
pillow-avif-plugin==1.4.6

```
Traceback (most recent call last):
  File "E:\Code\pixtral\test.py", line 265, in <module>
    process_batch(args.train_data_dir, args.systemprompt, args.api_key, args.dir_name, args.model_path)
  File "E:\Code\pixtral\test.py", line 72, in process_batch
    inputs = processor(images=images, text=prompts, return_tensors="pt").to(
  File "E:\Code\pixtral\.venv\lib\site-packages\transformers\models\pixtral\processing_pixtral.py", line 218, in __call__
    images = [[load_image(im) for im in sample] for sample in images]
  File "E:\Code\pixtral\.venv\lib\site-packages\transformers\models\pixtral\processing_pixtral.py", line 218, in <listcomp>
    images = [[load_image(im) for im in sample] for sample in images]
  File "E:\Code\pixtral\.venv\lib\site-packages\transformers\models\pixtral\processing_pixtral.py", line 218, in <listcomp>
    images = [[load_image(im) for im in sample] for sample in images]
  File "E:\Code\pixtral\.venv\lib\site-packages\transformers\image_utils.py", line 383, in load_image
    image = PIL.ImageOps.exif_transpose(image)
  File "E:\Code\pixtral\.venv\lib\site-packages\PIL\ImageOps.py", line 617, in exif_transpose
    image.load()
  File "E:\Code\pixtral\.venv\lib\site-packages\pillow_avif\AvifImagePlugin.py", line 95, in load
    data, timescale, tsp_in_ts, dur_in_ts = self._decoder.get_frame(
AttributeError: 'AvifImageFile' object has no attribute '_decoder'
```

**Comment by fdintino** [comment]
Are the PIL Image objects here being created in a standard way? If they came from a call to `PIL.Image.open` then this `AttributeError` shouldn't be possible.

**Comment by sdbds** [comment]
> Are the PIL Image objects here being created in a standard way? If they came from a call to `PIL.Image.open` then this `AttributeError` shouldn't be possible.

The original image is implemented by opening binary IO.
Image.open(io.BytesIO(raw_img["data"][0])

**Comment by fdintino** [comment]
Could you check to see whether you get a similar error with a webp image?
